# Funding options surfaced by the GitHub "Sponsor" button.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom: ["https://etherscan.io/address/0xB7AD723DDEF4Df973E898D36256E76Ab8489D57E"]
